services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contactbook-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3000}
      MONGO_URI: ${MONGO_URI_DOCKER}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:latest
    platform: linux/arm64/v8
    container_name: mongodb-community
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
